{{- range $index, $service := .Values.services}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .nameOverride }}
  labels:
    app: {{ .nameOverride }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .nameOverride }}
    spec:
      containers:
        - name: {{ .nameOverride }}
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .service.envs }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .mongodb }}
          - name: MONGODB_CONN_STR
            valueFrom:
              secretKeyRef:
                name: {{ .mongodb.connectionStringSecret }}
                key: connectionString.standard
          {{- end }}
          ports:
            - containerPort: {{ .service.port }}
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .nameOverride }}
  labels:
    app: {{ .nameOverride }}
spec:
  selector:
    app: {{ .nameOverride }}
  ports:
    - port: {{ .service.port }}
      protocol: TCP
      targetPort: {{ .service.port }}
  type: {{ .service.type }}
---

{{- end }}